Repository DDD-Community/DDD-9-WEB3-front, pull requests merged in 2023-08, with the labels that each got.

#1 setting: kakao map 세팅
  .gitignore
  package.json
  tsconfig.json
  yarn.lock
Labels: v1.0, setting

#2 chore: eslint 설정 및 @tanstack/react-query 설치
  .eslintrc.json
  .prettierrc
  app/_components/providers/ReactQueryProvider.tsx
  app/layout.tsx
  package.json
  yarn.lock
Labels: chore

#3 chore: github actions 추가
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.yml
  .github/workflows/assignor.yml
  .github/workflows/pr-labeler.yml
Labels: chore

#4 chore: types, assets 폴더 구조 변경
  app/_constants/index.ts
  app/_styles/fonts.ts
  app/_styles/icon.tsx
  app/_types/common/index.d.ts
  app/_types/types.ts
  next.config.js
  package.json
  public/assets/fonts/Pretendard-Bold.woff
  public/assets/fonts/Pretendard-Bold.woff2
  public/assets/fonts/Pretendard-Medium.woff
  public/assets/fonts/Pretendard-Medium.woff2
  public/assets/fonts/Pretendard-Regular.woff
  public/assets/fonts/Pretendard-Regular.woff2
  public/assets/svg/shopMarker.svg
  tsconfig.json
  yarn.lock
Labels: chore

#10 chore: husky, lint-staged, commitlint, stylelint 설치
  .husky/commit-msg
  .husky/pre-commit
  .stylelintrc
  .vscode/extensions.json
  .vscode/setting.json
  app/_styles/global.css
  commitlint.config.js
  package.json
  yarn.lock
Labels: v1.0, chore

#13 chore: 지도용 svg 생성
  .husky/pre-commit
  app/_constants/map/index.ts
  app/_lib/util/index.ts
  app/_styles/icon.tsx
  app/_types/common/index.d.ts
  app/_types/types.ts
  public/assets/svg/bookmarkIcon.svg
  public/assets/svg/bookmarkOff.svg
  public/assets/svg/bookmarkOn.svg
  public/assets/svg/bookmarker.svg
  public/assets/svg/location.svg
  public/assets/svg/lottoIcon.svg
  public/assets/svg/lottoMarkerSelect.svg
  public/assets/svg/minusIcon.svg
  public/assets/svg/myPosition.svg
  public/assets/svg/nearMe.svg
  public/assets/svg/plusIcon.svg
  public/assets/svg/shopIcon.svg
  public/assets/svg/shopMarker.svg
  public/assets/svg/shopMarkerSelect.svg
Labels: chore

#7 feat: 로그인 페이지 마크업 및 인증 로직 구현
  .env.example
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .stylelintrc
  .vscode/extensions.json
  .vscode/setting.json
  app/(router)/login/kakao/page.tsx
  app/(router)/login/page.tsx
  app/_apis/auth.ts
  app/_apis/core.ts
  app/_components/home/KakaoButton.tsx
  app/_components/home/LottoBallSlider.tsx
  app/_components/icons/IconClose.tsx
  app/_components/icons/IconKakao.tsx
  app/_constants/auth.ts
  app/_constants/http.ts
  app/_constants/routes.ts
  app/_features/LoginPage.tsx
  app/_hooks/useKakaoLogin.ts
  app/_store/auth.ts
  app/_styles/global.css
  app/_styles/palette.ts
  app/_types/auth.ts
  app/layout.tsx
  app/page.tsx
  commitlint.config.js
  package.json
  public/assets/images/lottoBall1.png
  public/assets/images/lottoBall2.png
  public/assets/images/lottoBall3.png
  public/next.svg
  public/vercel.svg
  tsconfig.json
  yarn.lock
Labels: v1.0, feature

#15 feat: 지도 페이지 마크업
  .env.example
  app/(router)/map/page.tsx
  app/_components/icons/IconMapType.tsx
  app/_components/map/ControlButton.tsx
  app/_components/map/MapTypeButton.tsx
  app/_constants/map/index.ts
  app/_features/MapPage.tsx
  public/assets/svg/bookmarkOn.svg
Labels: v1.0, feature

#16 feat: 카카오 소셜 로그인 구현
  app/(router)/login/kakao/page.tsx
  app/(router)/login/page.tsx
  app/_apis/core.ts
  app/_components/common/Navigation.tsx
  app/_components/common/Spinner.tsx
  app/_components/login/KakaoButton.tsx
  app/_components/login/LottoBallSlider.tsx
  app/_components/providers/AuthProvider.tsx
  app/_constants/auth.ts
  app/_features/LoginPage.tsx
  app/_hooks/useKakaoLogin.ts
  app/_styles/global.css
  app/page.tsx
Labels: feature

#17 feat: 분석 메인 페이지 마크업 및 기간별 분석페이지 제작중
  .eslintrc.json
  app/(router)/analysis/amount/page.tsx
  app/(router)/analysis/page.tsx
  app/(router)/analysis/period/page.tsx
  app/(router)/analysis/period/pick/page.tsx
  app/(router)/analysis/rounds/page.tsx
  app/_components/analysis/AnalysisMainWrapper.tsx
  app/_components/analysis/AnalyticsDashboardMenu.tsx
  app/_components/analysis/ResultAmountBannerList.tsx
  app/_components/analysis/Test.tsx
  app/_components/analysis/chart/BarChartWrapper.tsx
  app/_components/analysis/chart/DoughnutChartWrapper.tsx
  app/_components/analysis/period/PeriodicAnalysisDateBar.tsx
  app/_components/analysis/period/PeriodicAnalysisHub.tsx
  app/_components/analysis/period/PeriodicAnalysisTabs.tsx
  app/_components/analysis/period/pick/PeriodicDatePicker.tsx
  app/_styles/palette.ts
  app/_types/common/index.d.ts
  package.json
  public/assets/images/analysisMain.png
  public/assets/svg/amount.svg
  public/assets/svg/arrow.svg
  public/assets/svg/calendar.svg
  public/assets/svg/dateFilter.svg
  public/assets/svg/polygon.svg
  public/assets/svg/rounds.svg
  yarn.lock
Labels: feature

#21 feat: 자동 로그인 구현 및 401 에러 처리
  app/_apis/auth.ts
  app/_apis/core.ts
  app/_apis/member.ts
  app/_components/common/Navigation.tsx
  app/_components/providers/AuthProvider.tsx
  app/_constants/auth.ts
  app/_hooks/useKakaoLogin.ts
  app/_lib/util/storage.ts
  app/_types/response.ts
  next.config.js
  tsconfig.json
Labels: v1.0, feature

#22 feat: 회원가입, 로그인 로직 구현
  app/(router)/signup/page.tsx
  app/_apis/auth.ts
  app/_apis/core.ts
  app/_apis/member.ts
  app/_components/providers/AuthProvider.tsx
  app/_constants/auth.ts
  app/_constants/http.ts
  app/_features/LoginPage.tsx
  app/_features/SignupPage.tsx
  app/_hooks/useKakaoLogin.ts
  app/_lib/util/http.ts
  app/_lib/util/storage.ts
  app/_store/auth.ts
  app/_store/member.ts
  app/_types/response.ts
Labels: feature

#24 feat: 마이페이지 마크업 및 유저 정보 API 연동
  app/(router)/mypage/page.tsx
  app/_apis/core.ts
  app/_apis/member.ts
  app/_components/mypage/MenuButton.tsx
  app/_components/mypage/Profile.tsx
  app/_features/MyPage.tsx
  app/_hooks/queries/useMember.ts
  app/_lib/util/queryKey.ts
  app/_styles/palette.ts
  public/assets/svg/bookmarkOff.svg
  public/assets/svg/logout.svg
  public/assets/svg/rightArrow.svg
  public/assets/svg/withdraw.svg
Labels: feature
